apiVersion: v1
kind: Pod
metadata:
  name: postifyhq
spec:
  imagePullSecrets:
    - name: dockerhub-secret

  containers:
    - name: postifyhq
      image: topeshittu/postifyhq:v1
      ports:
        - containerPort: 80
